{
 "title": "Portworx Performance Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "px_cluster_cpu_percent" },
   {
    "name": "Instances",
    "label": "Node",
    "query": "px_cluster_cpu_percent{cluster=\"$Cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(px_volume_halevel{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Attached volumes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_attached{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Storage Offline",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_status_nodes_storage_down{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Avg HA Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_halevel {cluster=~\"$Cluster\"}) / count(px_volume_halevel{cluster=~\"$Cluster\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Total Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_total_bytes{cluster=~\"$Cluster\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Volume Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(px_volume_usage_bytes{})" }
   ]
  },
  {
   "title": "Filesystem Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_fs_usage_bytes{})"
    }
   ]
  },
  {
   "title": "IO Rate (Node Exporter)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m])) + sum(rate(node_disk_read_bytes_total{device=~\".+pxd.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Total Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "px_px_cache_total_blocks{}" }
   ]
  },
  {
   "title": "Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "px_px_cache_used_blocks{}" }
   ]
  },
  {
   "title": "Total Dirty",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "px_px_cache_dirty_blocks{}" },
    {}
   ]
  },
  {
   "title": "IO Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "px_px_cache_io_mbps{}" },
    {}
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network Sent (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Received (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Pending IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "rate(px_cluster_pendingio{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "expr": "rate(px_cluster_pendingio{cluster=~\"$Cluster\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Volume (Node Exporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Latency (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "- (rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "IOPS (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "-(rate(node_disk_reads_completed_total[1m])/rate(node_disk_read_time_seconds_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[1m])/rate(node_disk_write_time_seconds_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Throughput (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-(rate(node_disk_read_bytes_total[1m])/rate(node_disk_read_time_seconds_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])/rate(node_disk_write_time_seconds_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "-(px_volume_vol_read_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"})",
     "legendFormat": "{{node}}_{{volumeid}}"
    },
    {
     "expr": "px_volume_vol_write_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "-(rate(px_disk_stats_num_reads{cluster=~\"$Cluster\", instance=~\"$Instances\"}[1m]))",
     "legendFormat": "{{node}}_{{disk}}_read"
    },
    {
     "expr": "rate(px_disk_stats_num_writes{cluster=~\"$Cluster\", instance=~\"$Instances\"}[1m])",
     "legendFormat": "{{node}}_{{disk}}_write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-(rate(px_disk_stats_read_bytes_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]))",
     "legendFormat": "{{node}}_{{disk}}_read"
    },
    {
     "expr": "rate(px_disk_stats_written_bytes_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m])",
     "legendFormat": "{{node}}_{{disk}}_write"
    }
   ]
  },
  {
   "title": "PX Vol IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "px_volume_iops{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "PX Vol Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_volume_readthroughput{luster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{volumeid}}_write"
    },
    {
     "expr": "-(px_volume_writethroughput{cluster=~\"$Cluster\",instance=~\"$Instances\"})",
     "legendFormat": "{{node}}_{{volumeid}}_write"
    }
   ]
  },
  {
   "title": "Discarded Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "px_volume_discarded_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}/1024/1024",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  { "title": "Replica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "PX Vol Replica Flush Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(px_volume_replica_flush_ms_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]) / rate(px_volume_replica_flushes_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m])",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "PX Vol Replica Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(px_volume_replica_written_bytes_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]) / rate(px_volume_replica_write_ms_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m])",
     "legendFormat": "{{node}}_{{volumeid}}_write"
    },
    {
     "expr": "-(rate(px_volume_replica_read_bytes_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]) / rate(px_volume_replica_read_ms_total{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]))",
     "legendFormat": "{{node}}_{{volumeid}}_read"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "PX Pool Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_write_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}*1000",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "PX Pool Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_writethroughput{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "PX Pool Flush Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_flushms{cluster=~\"$Cluster\",instance=~\"$Instances\"}/px_pool_stats_num_flushes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "PX Pool Flush Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_flushed_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}/(px_pool_stats_flushms{cluster=~\"$Cluster\",instance=~\"$Instances\"}/1000)",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "IO Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_volume_dev_depth_io{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "Aggregate Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(px_disk_stats_written_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}[1m]))",
     "legendFormat": "pool"
    },
    {
     "expr": "sum(px_volume_writethroughput{cluster=~\"$Cluster\",instance=~\"$Instances\"})",
     "legendFormat": "volume"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m]))",
     "legendFormat": "px device"
    },
    {
     "expr": "sum(rate(px_disk_stats_written_bytes[1m]))/sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "PX Vol Long Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(px_volume_vol_written_bytes[1m]))"
    }
   ]
  },
  {
   "title": "PX Vol Long Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_reads{}", "legendFormat": "{{node}}_{{volumeid}}" }
   ]
  },
  {
   "title": "PX Vol Long Flushes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_flushes{}", "legendFormat": "{{node}}_{{volumeid}}" }
   ]
  },
  {
   "title": "Long IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "px_volume_num_long_writes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "legendFormat": "{{node}}_{{volumeid}}"
    },
    {
     "expr": "-(px_volume_num_long_reads{cluster=~\"$Cluster\",instance=~\"$Instances\"})",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  }
 ]
}