apiVersion: v1
kind: Service
metadata:
  name: alertmanager-portworx
  namespace: kube-test
spec:
  ports:
    - name: web
      port: 9093
      targetPort: 9093
  selector:
    alertmanager: portworx
