apiVersion: apps/v1
kind: Deployment
metadata:
  name: px-telemetry-metrics-collector
  namespace: kube-test
spec:
  replicas: 1
  selector:
    matchLabels:
      role: realtime-metrics-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: realtime-metrics-collector
        operator.libopenstorage.org/managed-by: portworx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: Exists
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - env:
        - name: CONFIG
          value: config/portworx.yaml
        image: docker.io/purestorage/realtime-metrics:latest
        imagePullPolicy: Always
        name: collector
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
        securityContext:
          runAsUser: 1111
        volumeMounts:
        - mountPath: /config
          name: px-collector-config
          readOnly: true
      - args:
        - envoy
        - "--base-id"
        - "4"
        - --config-path
        - /config/envoy-config.yaml
        image: docker.io/purestorage/envoy:1.2.3
        imagePullPolicy: Always
        name: envoy
        securityContext:
          runAsUser: 1111
        volumeMounts:
        - mountPath: /config
          name: px-collector-proxy-config
          readOnly: true
        - mountPath: /appliance-cert
          name: pure-telemetry-certs
          readOnly: true
        - mountPath: /etc/envoy/
          name: tls-certificate
          readOnly: true
      initContainers:
      - args:
        - cert_checker
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.io/purestorage/envoy:1.2.3
        imagePullPolicy: Always
        name: init-cont
        securityContext:
          runAsUser: 1111
      serviceAccountName: px-telemetry
      volumes:
      - configMap:
          name: px-telemetry-collector
        name: px-collector-config
      - configMap:
          name: px-telemetry-collector-proxy
        name: px-collector-proxy-config
      - name: pure-telemetry-certs
        secret:
          secretName: pure-telemetry-certs
      - configMap:
          name: px-telemetry-tls-certificate
        name: tls-certificate