apiVersion: v1
kind: ConfigMap
metadata:
  name: px-telemetry-register-proxy
  namespace: kube-test
  ownerReferences:
  - apiVersion: core.libopenstorage.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: StorageCluster
data:
  envoy-config-register.yaml: |-
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    node:
      id: "id_register"
      cluster: "cluster_register"
    static_resources:
      listeners:
      - name: listener_register_cloud_support
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 13001
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    request_headers_to_add:
                    - header:
                        key: "product-name"
                        value: "portworx"
                    - header:
                        key: "appliance-id"
                        value: test-clusteruid
                    - header:
                        key: "component-sn"
                        value: px-cluster
                    - header:
                        key: "product-version"
                        value: 2.12.0
                    route:
                      host_rewrite_literal: register.cloud-support.purestorage.com
                      cluster: cluster_register_cloud_support
      - name: listener_register_cloud_support_tcp_proxy
        address:
          socket_address:
            protocol: TCP
            address: 127.0.0.1
            port_value: 13003
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: ingress_register_tcp_proxy
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              cluster: cluster_register_cloud_support_tcp_proxy
      - name: listener_register_customer_proxy_envoy_internal_redirect
        address:
          socket_address:
            protocol: TCP
            address: 127.0.0.1
            port_value: 13005
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: ingress_register_customer_proxy_envoy_internal_redirect
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              cluster: cluster_customer_proxy
              tunneling_config:
                hostname: register.cloud-support.purestorage.com:443
                headers_to_add:
                - header:
                    key: "product-name"
                    value: "portworx"
                - header:
                    key: "appliance-id"
                    value: test-clusteruid
                - header:
                    key: "component-sn"
                    value: px-cluster
                - header:
                    key: "product-version"
                    value: 2.12.0
      clusters:
      - name: cluster_register_cloud_support
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: cluster_register_cloud_support
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 13005
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                private_key:
      - name: cluster_register_cloud_support_tcp_proxy
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: cluster_register_cloud_support_tcp_proxy
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 13005
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                private_key:
      - name: cluster_customer_proxy
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        # This ensures HTTP/1.1 CONNECT is used for establishing the tunnel.
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http_protocol_options: {}
        load_assignment:
          cluster_name: cluster_customer_proxy
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: hostname
                    port_value: 1234
