apiVersion: v1
kind: ConfigMap
metadata:
  name: px-telemetry-collector
  namespace: kube-test
  ownerReferences:
  - apiVersion: core.libopenstorage.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: StorageCluster
data:
  portworx.yaml: |-
    scrapeConfig:
      interval: 10
      k8sConfig:
        pods:
        - podSelector:
            name: portworx
          namespace: kube-test
          endpoint: metrics
          port: 10001
    forwardConfig:
      url: http://localhost:11000/metrics/1.0/pure1-metrics-pb