apiVersion: v1
kind: Pod
metadata:
  name: portworx-kvdb-jhjrc
  namespace: kube-system
spec:
  hostNetwork: true
  hostPID: false
  containers:
    - name: portworx-kvdb
      image: registry.k8s.io/pause:3.1
      imagePullPolicy: Always
      livenessProbe:
        periodSeconds: 30
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
        initialDelaySeconds: 840
        tcpSocket:
          host: 127.0.0.1
          port: 9019
      readinessProbe:
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
        tcpSocket:
          host: 127.0.0.1
          port: 9019
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 100Mi
  restartPolicy: Always
  serviceAccountName: portworx
