kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: px-lighthouse
  namespace: kube-test
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["stork.libopenstorage.org"]
    resources: ["clusterpairs","migrations"]
    verbs: ["get", "list", "create", "delete", "update"]
