apiVersion: v1
kind: Service
metadata:
  name: px-lighthouse
  namespace: kube-test
  labels:
    tier: px-web-console
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    tier: px-web-console
