kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: px-node-wiper
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["portworx"]
  verbs: ["use"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["px-privileged"]
  verbs: ["use"]