apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portworx-api
  namespace: kube-test
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      name: portworx-api
  template:
    metadata:
      labels:
        operator.libopenstorage.org/managed-by: portworx
        name: portworx-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: kubernetes.io/os
                operator: In
                values:
                - "linux"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      hostPID: false
      containers:
        - name: portworx-api
          image: registry.k8s.io/pause:3.1
          imagePullPolicy: Always
          readinessProbe:
            periodSeconds: 10
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 10001
        - args:
          - --v=5
          - --csi-address=$(ADDRESS)
          - --kubelet-registration-path=/var/lib/kubelet/csi-plugins/pxd.portworx.com/csi.sock
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: ""
                fieldPath: spec.nodeName
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.3
          imagePullPolicy: Always
          name: csi-node-driver-registrar
          resources: {}
          terminationMessagePath: ""
          terminationMessagePolicy: ""
          volumeMounts:
          - mountPath: /csi
            name: csi-driver-path
          - mountPath: /registration
            name: registration-dir
      restartPolicy: Always
      serviceAccountName: portworx
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/csi-plugins/pxd.portworx.com
          type: DirectoryOrCreate
        name: csi-driver-path
