kind: Service
apiVersion: v1
metadata:
  name: portworx-service
  namespace: kube-test
  labels:
    name: portworx
spec:
  selector:
    name: portworx
  type: ClusterIP
  ports:
    - name: px-api
      protocol: TCP
      port: 9001
      targetPort: 10001
    - name: px-kvdb
      protocol: TCP
      port: 9019
      targetPort: 10019
    - name: px-sdk
      protocol: TCP
      port: 9020
      targetPort: 10020
    - name: px-rest-gateway
      protocol: TCP
      port: 9021
      targetPort: 10021
