kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portworx
  namespace: kube-test
subjects:
- kind: ServiceAccount
  name: portworx
  namespace: kube-test
roleRef:
  kind: Role
  name: portworx
  apiGroup: rbac.authorization.k8s.io
