apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: px-privileged
spec:
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  privileged: true
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - secret
  - hostPath
  - emptyDir
