apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: px-prometheus
  namespace: kube-test
spec:
  replicas: 1
  logLevel: debug
  serviceAccountName: px-prometheus
  image: quay.io/prometheus/prometheus:v1.2.3
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - portworx
      - px-backup
  remoteWrite:
  - url: "test.endpoint:1234/api/prom/push"
  resources:
    requests:
      memory: 400Mi
    limits:
      cpu: 1
      ephemeral-storage: 5Gi
      memory: 800Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  ruleSelector:
    matchLabels:
      prometheus: portworx
