apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: px-prometheus
  namespace: kube-test
spec:
  replicas: 1
  logLevel: debug
  serviceAccountName: px-prometheus
  image: quay.io/prometheus/prometheus:v2.7.1
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - portworx
      - px-backup
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: portworx
