# For k8s 1.22+ with newer version Prometheus operator
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: px-prometheus-operator
  name: px-prometheus-operator
  namespace: kube-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: px-prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: px-prometheus-operator
    spec:
      containers:
        - args:
            - -namespaces=kube-test
            - --kubelet-service=kube-test/kubelet
            - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.50.0
          image: quay.io/prometheus-operator/prometheus-operator:v0.50.0
          imagePullPolicy: Always
          name: px-prometheus-operator
          ports:
            - containerPort: 8080
              name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: px-prometheus-operator
