apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: px-prometheus
  namespace: kube-test
spec:
  replicas: 1
  podMetadata:
    labels:
      operator.libopenstorage.org/managed-by: portworx
  logLevel: debug
  serviceAccountName: px-prometheus
  image: quay.io/prometheus/prometheus:v1.2.3
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - portworx
      - px-backup
  alerting:
    alertmanagers:
    - namespace: kube-test
      name: alertmanager-portworx
      port: web
  resources:
    requests:
      memory: 400Mi
    limits:
      cpu: 1
      ephemeral-storage: 5Gi
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  ruleSelector:
    matchLabels:
      prometheus: portworx
