apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: px-prometheus-operator
  name: px-prometheus-operator
  namespace: kube-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: px-prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: px-prometheus-operator
    spec:
      containers:
        - args:
            - -namespaces=kube-test
            - --kubelet-service=kube-test/kubelet
            - --config-reloader-image=quay.io/coreos/configmap-reload:v1.2.3
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v1.2.3
          image: quay.io/coreos/prometheus-operator:v1.2.3
          imagePullPolicy: Always
          name: px-prometheus-operator
          ports:
            - containerPort: 8080
              name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: px-prometheus-operator
