kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portworx-pvc-controller
subjects:
- kind: ServiceAccount
  name: portworx-pvc-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: portworx-pvc-controller
  apiGroup: rbac.authorization.k8s.io
