apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: px-csi-win-driver
  labels:
    app: px-csi-win-driver
spec:
  selector:
    matchLabels:
      app: px-csi-win-driver
  template:
    metadata:
      labels:
        app: px-csi-win-driver
        operator.libopenstorage.org/managed-by: portworx
    spec:
      serviceAccountName: portworx
      containers:
        - name: windowsinstaller
          image: docker.io/portworx/px-windows-csi-driver:23.8.0
          imagePullPolicy: Always
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
          command:
            - powershell.exe
            - -command
            - csidriver\\pxinstall.ps1
      hostNetwork: true