kind: Service
apiVersion: v1
metadata:
  name: portworx-service
  namespace: kube-system
  labels:
    name: portworx-proxy
spec:
  selector:
    name: portworx-proxy
  type: ClusterIP
  ports:
    - name: px-api
      protocol: TCP
      port: 9001
      targetPort: 10001
    - name: px-kvdb
      protocol: TCP
      port: 9019
      targetPort: 10016
    - name: px-sdk
      protocol: TCP
      port: 9020
      targetPort: 10017
    - name: px-rest-gateway
      protocol: TCP
      port: 9021
      targetPort: 10018
