kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portworx-proxy
subjects:
- kind: ServiceAccount
  name: portworx-proxy
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: portworx
  apiGroup: rbac.authorization.k8s.io
