apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: resource-gateway
    tier: control-plane
  name: resource-gateway
  namespace: kube-test
  ownerReferences:
    - apiVersion: core.libopenstorage.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: StorageCluster
      name: px-cluster
spec:
  selector:
    matchLabels:
      name: resource-gateway
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        name: resource-gateway
        tier: control-plane
    spec:
      serviceAccountName: resource-gateway
      containers:
      - name: resource-gateway
        image: docker.io/portworx/operator:1.1.1
        imagePullPolicy: Always
        command:
        - /resource-gateway
        - --namespace=kube-test
        - --serverHost=0.0.0.0
        - --serverPort=50051
        securityContext:
          allowPrivilegeEscalation: false       
          privileged: false
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 2
        ports:
        - containerPort: 50051
          name: resource-gate
          protocol: TCP