apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: px-restricted
spec:
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - secret
  - hostPath
  - emptyDir
