kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-db-encrypted
  annotations:
    params/note: "Ensure that you have a cluster-wide secret created in the configured secrets provider"
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  secure: "true"
  io_profile: "db"
