kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-db-local-snapshot-encrypted
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  secure: "true"
  snapshotschedule.stork.libopenstorage.org/daily-schedule: |
    schedulePolicyName: default-daily-policy
    annotations:
      portworx/snapshot-type: local
allowVolumeExpansion: true
