kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-db-cloud-snapshot
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  snapshotschedule.stork.libopenstorage.org/daily-schedule: |
    schedulePolicyName: default-daily-policy
    annotations:
      portworx/snapshot-type: cloud
