kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-csi-db-local-snapshot
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  io_profile: "db_remote"
  snapshotschedule.stork.libopenstorage.org/daily-schedule: |
    schedulePolicyName: default-daily-policy
    annotations:
      portworx/snapshot-type: local
allowVolumeExpansion: true
