# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/gengo/args",
  "k8s.io/gengo/generator",
  "k8s.io/gengo/examples/defaulter-gen/generators",
  "k8s.io/code-generator/cmd/defaulter-gen/args",
  "k8s.io/code-generator/cmd/deepcopy-gen/args",
  "github.com/golang/protobuf/protoc-gen-go",
]

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "v0.10.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.2.2"

[[constraint]]
  name = "github.com/portworx/sched-ops"
  branch = "master"

[[constraint]]
  name = "github.com/libopenstorage/openstorage"
  branch = "release-6.0"

[[override]]
  name = "github.com/libopenstorage/stork"
  branch = "master"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.14.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.6"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.6"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "v0.29.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.3.0"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  go-tests = false
