actKeyRequired: false
cert:
  keySize: 2048
  renewWindowInDays: 30
  registrationEnabled: true
  renewEnabled: true
  keyAlgorithm: "RSA"
  noRelCertEnabled: true
  release:
    staging:
      private: "/opt/ccm/cert/rel_priv_staging.pem"
    production:
      private: "/opt/ccm/cert/rel_priv.pem"
subscription:
  useApplianceId: true
  accountType: "UNKNOWN"
standalone:
  applianceIdPath: "/var/cache/appliance_id"
  generateApplianceIdEnabled: false
envoy:
  protocol: "http"
  registrationHost: "localhost"
  registrationPort: "REGISTER_CLOUD_SUPPORT_PORT"
  renewalHost: "localhost"
  renewalPort: "REST_CLOUD_SUPPORT_PORT"
cloud:
  auth:
    version: "1.0"
productName: "portworx"
certStoreType: "k8s"
k8s:
  certSecretName: "pure-telemetry-certs"
  certSecretNamespace: CERT_SECRET_NAMESPACE