apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: px-telemetry-stc-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: px-telemetry-stc-reader
subjects:
- kind: ServiceAccount
  name: px-telemetry
  apiGroup: ""
  namespace: kube-system