apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: px-telemetry-stc-reader
rules:
- apiGroups: ["core.libopenstorage.org"]
  resources: ["storageclusters"]
  verbs: ["get", "list"]