apiVersion: batch/v1
kind: Job
metadata:
  name: px-k8s-retriever-job
spec:
  template:
    spec:
      serviceAccountName: portworx-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
        - name: k8s-retriever
          image: portworx/px-operator:latest
          env:
          - name: "OUTPUT_PATH"
            value: "/var/cores"
          - name: "PX_NAMESPACE"
            value: "portworx"
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          command: ["/bin/sh", "-c", "/app/retriever --output_dir $OUTPUT_PATH --namespace $PX_NAMESPACE"]
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: log-volume
              mountPath: /var/cores/px-k8s-retriever
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1500m
              memory: 2Gi
      restartPolicy: OnFailure
      volumes:
        - name: log-volume
          hostPath:
            path: /var/cores/px-k8s-retriever
            type: DirectoryOrCreate