/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/libopenstorage/operator/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterOperations implements ClusterOperationInterface
type FakeClusterOperations struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var clusteroperationsResource = schema.GroupVersionResource{Group: "core.libopenstorage.org", Version: "v1alpha1", Resource: "clusteroperations"}

var clusteroperationsKind = schema.GroupVersionKind{Group: "core.libopenstorage.org", Version: "v1alpha1", Kind: "ClusterOperation"}

// Get takes name of the clusterOperation, and returns the corresponding clusterOperation object, and an error if there is any.
func (c *FakeClusterOperations) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusteroperationsResource, c.ns, name), &v1alpha1.ClusterOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOperation), err
}

// List takes label and field selectors, and returns the list of ClusterOperations that match those selectors.
func (c *FakeClusterOperations) List(opts v1.ListOptions) (result *v1alpha1.ClusterOperationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusteroperationsResource, clusteroperationsKind, c.ns, opts), &v1alpha1.ClusterOperationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterOperationList{ListMeta: obj.(*v1alpha1.ClusterOperationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterOperationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterOperations.
func (c *FakeClusterOperations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusteroperationsResource, c.ns, opts))

}

// Create takes the representation of a clusterOperation and creates it.  Returns the server's representation of the clusterOperation, and an error, if there is any.
func (c *FakeClusterOperations) Create(clusterOperation *v1alpha1.ClusterOperation) (result *v1alpha1.ClusterOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusteroperationsResource, c.ns, clusterOperation), &v1alpha1.ClusterOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOperation), err
}

// Update takes the representation of a clusterOperation and updates it. Returns the server's representation of the clusterOperation, and an error, if there is any.
func (c *FakeClusterOperations) Update(clusterOperation *v1alpha1.ClusterOperation) (result *v1alpha1.ClusterOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusteroperationsResource, c.ns, clusterOperation), &v1alpha1.ClusterOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOperation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterOperations) UpdateStatus(clusterOperation *v1alpha1.ClusterOperation) (*v1alpha1.ClusterOperation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusteroperationsResource, "status", c.ns, clusterOperation), &v1alpha1.ClusterOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOperation), err
}

// Delete takes name of the clusterOperation and deletes it. Returns an error if one occurs.
func (c *FakeClusterOperations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusteroperationsResource, c.ns, name), &v1alpha1.ClusterOperation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterOperations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusteroperationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterOperationList{})
	return err
}

// Patch applies the patch and returns the patched clusterOperation.
func (c *FakeClusterOperations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusteroperationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOperation), err
}
