apiVersion: core.libopenstorage.org/v1alpha1
kind: StorageCluster
metadata:
  name: portworx
  namespace: kube-system
  annotations:
    portworx.io/is-openshift: "true"
spec:
  image: 'registry.connect.redhat.com/portworx/px-monitor:2.1.2-rc1'
  kvdb:
    internal: true
  storage:
    useAll: true
