apiVersion: core.libopenstorage.org/v1alpha1
kind: StorageCluster
metadata:
  name: portworx
  namespace: kube-system
  annotations:
  - portworx.io/is-openshift: "true"
spec:
  image: 'portworx/oci-monitor:2.0.3.3'
  kvdb:
    internal: true
  storage:
    devices:
      useAll: true
