apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: px-operator
spec:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  volumes:
  - secret
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'