---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: retrieve-multipath-conf
  labels:
    app: retrieve-multipath-conf
spec:
  selector:
    matchLabels:
      name: retrieve-multipath-conf
  template:
    metadata:
      labels:
        name: retrieve-multipath-conf
    spec:
      containers:
        - name: retrieve-multipath-conf
          image: busybox:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo Node: $NODE_NAME; echo ========================; echo File: /etc/multipath.conf; echo ' '; cat /etc/multipath.conf; echo ========================; sleep 3600; done"]
          env:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /etc
              name: etc
              readOnly: true
      volumes:
        - hostPath:
            path: /etc
            type: Directory
          name: etc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: px-k8s-retriever-job
spec:
  template:
    spec:
      serviceAccountName: portworx-operator
      containers:
        - name: k8s-retriever
          image: calvarado2004/portworx-operator:23.12.0
          command:
            - /bin/sh
            - -c
            - /support/scripts/bin/retriever
          env:
            - name: "PX_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "RETRIEVER_OUTPUT_PATH"
              value: "/var/cores/px-k8s-retriever"
            - name: "RETRIEVER_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "RETRIEVER_NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: cores-volume
              mountPath: /var/cores
      restartPolicy: OnFailure
      volumes:
        - name: cores-volume
          hostPath:
            path: /var/cores
            type: Directory