---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: retrieve-multipath-conf
  labels:
    app: retrieve-multipath-conf
spec:
  selector:
    matchLabels:
      name: retrieve-multipath-conf
  template:
    metadata:
      labels:
        name: retrieve-multipath-conf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
              - matchExpressions:
                  - key: px/enabled
                    operator: NotIn
                    values:
                      - 'false'
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
        - name: retrieve-multipath-conf
          image: busybox:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo Node: $NODE_NAME; echo ========================; echo File: /etc/multipath.conf; echo ' '; cat /etc/multipath.conf; echo ========================; sleep 10; done"]
          env:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /etc
              name: etc
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 150Mi
      volumes:
        - hostPath:
            path: /etc
            type: Directory
          name: etc