/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	corev1 "github.com/libopenstorage/operator/pkg/apis/core/v1"
	versioned "github.com/libopenstorage/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/libopenstorage/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/libopenstorage/operator/pkg/client/listers/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StorageNodeInformer provides access to a shared informer and lister for
// StorageNodes.
type StorageNodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.StorageNodeLister
}

type storageNodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStorageNodeInformer constructs a new informer for StorageNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStorageNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStorageNodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStorageNodeInformer constructs a new informer for StorageNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStorageNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().StorageNodes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().StorageNodes(namespace).Watch(context.TODO(), options)
			},
		},
		&corev1.StorageNode{},
		resyncPeriod,
		indexers,
	)
}

func (f *storageNodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStorageNodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *storageNodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1.StorageNode{}, f.defaultInformer)
}

func (f *storageNodeInformer) Lister() v1.StorageNodeLister {
	return v1.NewStorageNodeLister(f.Informer().GetIndexer())
}
