/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	portworxv1 "github.com/libopenstorage/operator/pkg/apis/portworx/v1"
	versioned "github.com/libopenstorage/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/libopenstorage/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/libopenstorage/operator/pkg/client/listers/portworx/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PortworxDiagInformer provides access to a shared informer and lister for
// PortworxDiags.
type PortworxDiagInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PortworxDiagLister
}

type portworxDiagInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPortworxDiagInformer constructs a new informer for PortworxDiag type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPortworxDiagInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPortworxDiagInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPortworxDiagInformer constructs a new informer for PortworxDiag type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPortworxDiagInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PortworxV1().PortworxDiags(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PortworxV1().PortworxDiags(namespace).Watch(context.TODO(), options)
			},
		},
		&portworxv1.PortworxDiag{},
		resyncPeriod,
		indexers,
	)
}

func (f *portworxDiagInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPortworxDiagInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *portworxDiagInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&portworxv1.PortworxDiag{}, f.defaultInformer)
}

func (f *portworxDiagInformer) Lister() v1.PortworxDiagLister {
	return v1.NewPortworxDiagLister(f.Informer().GetIndexer())
}
