/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	portworxv1 "github.com/libopenstorage/operator/pkg/apis/portworx/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePortworxDiags implements PortworxDiagInterface
type FakePortworxDiags struct {
	Fake *FakePortworxV1
	ns   string
}

var portworxdiagsResource = schema.GroupVersionResource{Group: "portworx.io", Version: "v1", Resource: "portworxdiags"}

var portworxdiagsKind = schema.GroupVersionKind{Group: "portworx.io", Version: "v1", Kind: "PortworxDiag"}

// Get takes name of the portworxDiag, and returns the corresponding portworxDiag object, and an error if there is any.
func (c *FakePortworxDiags) Get(ctx context.Context, name string, options v1.GetOptions) (result *portworxv1.PortworxDiag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(portworxdiagsResource, c.ns, name), &portworxv1.PortworxDiag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*portworxv1.PortworxDiag), err
}

// List takes label and field selectors, and returns the list of PortworxDiags that match those selectors.
func (c *FakePortworxDiags) List(ctx context.Context, opts v1.ListOptions) (result *portworxv1.PortworxDiagList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(portworxdiagsResource, portworxdiagsKind, c.ns, opts), &portworxv1.PortworxDiagList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &portworxv1.PortworxDiagList{ListMeta: obj.(*portworxv1.PortworxDiagList).ListMeta}
	for _, item := range obj.(*portworxv1.PortworxDiagList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested portworxDiags.
func (c *FakePortworxDiags) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(portworxdiagsResource, c.ns, opts))

}

// Create takes the representation of a portworxDiag and creates it.  Returns the server's representation of the portworxDiag, and an error, if there is any.
func (c *FakePortworxDiags) Create(ctx context.Context, portworxDiag *portworxv1.PortworxDiag, opts v1.CreateOptions) (result *portworxv1.PortworxDiag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(portworxdiagsResource, c.ns, portworxDiag), &portworxv1.PortworxDiag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*portworxv1.PortworxDiag), err
}

// Update takes the representation of a portworxDiag and updates it. Returns the server's representation of the portworxDiag, and an error, if there is any.
func (c *FakePortworxDiags) Update(ctx context.Context, portworxDiag *portworxv1.PortworxDiag, opts v1.UpdateOptions) (result *portworxv1.PortworxDiag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(portworxdiagsResource, c.ns, portworxDiag), &portworxv1.PortworxDiag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*portworxv1.PortworxDiag), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePortworxDiags) UpdateStatus(ctx context.Context, portworxDiag *portworxv1.PortworxDiag, opts v1.UpdateOptions) (*portworxv1.PortworxDiag, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(portworxdiagsResource, "status", c.ns, portworxDiag), &portworxv1.PortworxDiag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*portworxv1.PortworxDiag), err
}

// Delete takes name of the portworxDiag and deletes it. Returns an error if one occurs.
func (c *FakePortworxDiags) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(portworxdiagsResource, c.ns, name, opts), &portworxv1.PortworxDiag{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePortworxDiags) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(portworxdiagsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &portworxv1.PortworxDiagList{})
	return err
}

// Patch applies the patch and returns the patched portworxDiag.
func (c *FakePortworxDiags) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *portworxv1.PortworxDiag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(portworxdiagsResource, c.ns, name, pt, data, subresources...), &portworxv1.PortworxDiag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*portworxv1.PortworxDiag), err
}
