/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"time"

	v1alpha2 "github.com/libopenstorage/operator/pkg/apis/core/v1alpha2"
	scheme "github.com/libopenstorage/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageNodeStatusesGetter has a method to return a StorageNodeStatusInterface.
// A group's client should implement this interface.
type StorageNodeStatusesGetter interface {
	StorageNodeStatuses(namespace string) StorageNodeStatusInterface
}

// StorageNodeStatusInterface has methods to work with StorageNodeStatus resources.
type StorageNodeStatusInterface interface {
	Create(*v1alpha2.StorageNodeStatus) (*v1alpha2.StorageNodeStatus, error)
	Update(*v1alpha2.StorageNodeStatus) (*v1alpha2.StorageNodeStatus, error)
	UpdateStatus(*v1alpha2.StorageNodeStatus) (*v1alpha2.StorageNodeStatus, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.StorageNodeStatus, error)
	List(opts v1.ListOptions) (*v1alpha2.StorageNodeStatusList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.StorageNodeStatus, err error)
	StorageNodeStatusExpansion
}

// storageNodeStatuses implements StorageNodeStatusInterface
type storageNodeStatuses struct {
	client rest.Interface
	ns     string
}

// newStorageNodeStatuses returns a StorageNodeStatuses
func newStorageNodeStatuses(c *CoreV1alpha2Client, namespace string) *storageNodeStatuses {
	return &storageNodeStatuses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storageNodeStatus, and returns the corresponding storageNodeStatus object, and an error if there is any.
func (c *storageNodeStatuses) Get(name string, options v1.GetOptions) (result *v1alpha2.StorageNodeStatus, err error) {
	result = &v1alpha2.StorageNodeStatus{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageNodeStatuses that match those selectors.
func (c *storageNodeStatuses) List(opts v1.ListOptions) (result *v1alpha2.StorageNodeStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.StorageNodeStatusList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageNodeStatuses.
func (c *storageNodeStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storageNodeStatus and creates it.  Returns the server's representation of the storageNodeStatus, and an error, if there is any.
func (c *storageNodeStatuses) Create(storageNodeStatus *v1alpha2.StorageNodeStatus) (result *v1alpha2.StorageNodeStatus, err error) {
	result = &v1alpha2.StorageNodeStatus{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		Body(storageNodeStatus).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storageNodeStatus and updates it. Returns the server's representation of the storageNodeStatus, and an error, if there is any.
func (c *storageNodeStatuses) Update(storageNodeStatus *v1alpha2.StorageNodeStatus) (result *v1alpha2.StorageNodeStatus, err error) {
	result = &v1alpha2.StorageNodeStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		Name(storageNodeStatus.Name).
		Body(storageNodeStatus).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *storageNodeStatuses) UpdateStatus(storageNodeStatus *v1alpha2.StorageNodeStatus) (result *v1alpha2.StorageNodeStatus, err error) {
	result = &v1alpha2.StorageNodeStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		Name(storageNodeStatus.Name).
		SubResource("status").
		Body(storageNodeStatus).
		Do().
		Into(result)
	return
}

// Delete takes name of the storageNodeStatus and deletes it. Returns an error if one occurs.
func (c *storageNodeStatuses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageNodeStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagenodestatuses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storageNodeStatus.
func (c *storageNodeStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.StorageNodeStatus, err error) {
	result = &v1alpha2.StorageNodeStatus{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storagenodestatuses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
