apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-operator-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: storage-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "create", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "deployments"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["core.libopenstorage.org"]
    resources: ["storageclusters", "storageclusters/finalizers"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces", "serviceaccounts"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["endpoints", "services"]
    verbs: ["get", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "delete", "update", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["privileged"]
    verbs: ["use"]
  - apiGroups: ["portworx.io"]
    resources: ["volumeplacementstrategies"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-operator-role-binding
subjects:
- kind: ServiceAccount
  name: storage-operator-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: storage-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    tier: control-plane
  name: storage-operator
  namespace: kube-system
  initializers:
    pending: []
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        tier: control-plane
        name: storage-operator
    spec:
      containers:
      - command:
        - /operator
        - --verbose
        - --driver=pxd
        - --leader-elect=true
        imagePullPolicy: Always
        image: piyushpx/openstorage-operator:latest
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        name: storage-operator
      hostPID: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - storage-operator
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: storage-operator-account
