apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-operator-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: storage-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "create", "patch", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["controllerrevisions"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["core.libopenstorage.org"]
    resources: ["storageclusters", "storageclusters/finalizers"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-operator-role-binding
subjects:
- kind: ServiceAccount
  name: storage-operator-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: storage-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    tier: control-plane
  name: storage-operator
  namespace: kube-system
  initializers:
    pending: []
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        tier: control-plane
        name: storage-operator
    spec:
      containers:
      - command:
        - /operator
        - --verbose
        - --driver=portworx
        - --leader-elect=true
        imagePullPolicy: Always
        image: piyushpx/openstorage-operator:latest
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        name: storage-operator
      hostPID: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - storage-operator
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: storage-operator-account
