kind: Service
apiVersion: v1
metadata:
  name: stork-service
  namespace: kube-test
spec:
  type: ClusterIP
  selector:
    name: stork
  ports:
  - name: extender
    protocol: TCP
    port: 8099
    targetPort: 8099
  - name: webhook
    protocol: TCP
    port: 443
    targetPort: 443
