kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: stork
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["px-restricted"]
    verbs: ["use"]
