kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stork-scheduler
subjects:
- kind: ServiceAccount
  name: stork-scheduler
  namespace: kube-test
roleRef:
  kind: ClusterRole
  name: stork-scheduler
  apiGroup: rbac.authorization.k8s.io
