apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageclusters.core.libopenstorage.org
spec:
  group: core.libopenstorage.org
  names:
    kind: StorageCluster
    listKind: StorageClusterList
    plural: storageclusters
    singular: storagecluster
    shortNames:
    - stc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata: {}
        spec:
          properties:
            image:
              type: string
            imagePullPolicy:
              type: string
            imagePullSecret: {}
            secretsProvider: {}
            startPort: {}
            updateStrategy: {}
            revisionHistoryLimit: {}
            placement: {}
            kvdb:
              properties:
                internal:
                  type: boolean
                endpoints: {}
                authSecret:
                  type: string
            storage:
              properties:
                useAll: {}
                useAllWithPartitions: {}
                forceUseDisks: {}
                devices: {}
                journalDevice: {}
                systemMetadataDevice: {}
                dataStorageType: {}
                raidLevel: {}
            cloudStorage:
              properties:
                maxStorageNodes:
                  type: int32
                maxStorageNodesPerZone:
                  type: int32
                deviceSpecs: {}
                journalDeviceSpec:
                  type: string
                systemMetadataDeviceSpec:
                  type: string
            network:
              properties:
                dataInterface:
                  type: string
                mgmtInterface:
                  type: string
            env: {}
        status:
          properties:
            clusterName:
              type: string
