# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Review requested
on:
  pull_request_target:
    types: [review_requested]
jobs:
  review-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: stage/in-review
        github_token: "${{ secrets.GITHUB_TOKEN }}"
